sudo: required
services:
  - docker  

before_install:
  - docker build -t slackman/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run slackman/react-test npm test -- --coverage

after_success:
  - docker build -t slackman/complex-client ./client
  - docker build -t slackman/complex-nginx  ./nginx
  - docker build -t slackman/complex-server ./server
  - docker build -t slackman/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push slackman/complex-client
  - docker push slackman/complex-nginx
  - docker push slackman/complex-server
  - docker push slackman/complex-worker